[target.x86_64-unknown-linux-gnu]
image = "patrickelectric/cross-rs:x86_64-unknown-linux-gnu-bookworm-slim-with-gstreamer"

[target.armv7-unknown-linux-gnueabihf]
image = "patrickelectric/cross-rs:armv7-unknown-linux-gnueabihf-bookworm-slim-with-gstreamer"