name: Deploy unix

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            TARGET: x86_64-unknown-linux-gnu
            SUFFIX: x86_64

          - os: ubuntu-22.04
            TARGET: armv7-unknown-linux-gnueabihf
            SUFFIX: armv7

          - os: ubuntu-22.04
            TARGET: aarch64-unknown-linux-gnu
            SUFFIX: aarch64

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set directory to safe for git
      # Note: Required by vergen (https://crates.io/crates/vergen)
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Use cached dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: "${{ matrix.os }}-${{ matrix.TARGET }}-${{ hashFiles('**/Cargo.lock') }}"
        shared-key: "shared"

    - uses: actions/checkout@master
    - name: Install build dependencies - Rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable --profile default --target ${{ matrix.TARGET }} -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    # Ref: https://github.com/cross-rs/cross/issues/1510
    - name: Install cross for linux
      if: contains(matrix.TARGET, 'linux')
      run: |
        cargo install cross

    - name: Building for ${{ matrix.os }} ${{ matrix.target }} (${{ matrix.SUFFIX }})
      run: cross build --release --locked --target ${{matrix.target}} --verbose

    - name: Prepare files
      run: |
        UPLOAD_DIR=$PWD/upload
        mkdir -p $UPLOAD_DIR

        TARGETDIR="target/${{ matrix.TARGET }}/release/"
        cd $TARGETDIR
        tar -cvf $UPLOAD_DIR/libgstqrtimestamp.so.tar libgstqrtimestamp.so

    - uses: actions/upload-artifact@v4
      with:
        name: libgstqrtimestamp-${{ matrix.SUFFIX }}.so.tar
        path: upload/*

    - uses: svenstaro/upload-release-action@v2
      name: Upload binaries to release
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')}}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: 'upload/libgstqrtimestamp-*'
        asset_name: libgstqrtimestamp-${{ matrix.SUFFIX }}
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
