name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install build dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: |
          libunwind-dev \
          libclang-dev \
          pkg-config \
          build-essential \
          curl \
          wget \
          gnupg \
          git \
          ca-certificates \
          libgit2-dev \
          libmount-dev \
          libsepol-dev \
          libselinux1-dev \
          libglib2.0-dev \
          libgudev-1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgstreamer1.0-dev

    - name: Checkout
      uses: actions/checkout@v4

    - name: Use cached dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: "${{ hashFiles('**/Cargo.lock') }}"
        shared-key: "shared"

    - name: Install build dependencies - Rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Check style
      run: cargo fmt --check

    - name: Check clippy
      run: cargo clippy --all-features --locked

    - name: Build
      run: cargo build --verbose --locked

    - name: Install runtime dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: |
          gstreamer1.0-tools

    - name: Run tests
      run: cargo test --verbose --locked -- --nocapture
